### ISSUE TITLE
[clock.lua] change the button setting to on/off

### ISSUE THREAD

**Issue by godhand19** [zenwarr/mpv-config#10]
In advance, thanks for creating this. I have a problem, i can't use f12 key to on/off (not working). Is there a way to change the button?

**Comment by zenwarr** [comment]
Yes, all you have to do is to find the following line in `input.conf` file:

```
F12 script-message-to clock toggle
```

Then change F12 to whatever key or shortcut you prefer.

**Comment by godhand19** [comment]
ahh thanks man.. it works! You're the best 👊
