### ISSUE TITLE
It didn't work

### ISSUE THREAD

**Issue by tXJtqlb3bbeKD1yW8SV7** [zenwarr/mpv-config#2]
How am I supposed to arrange all these files (`script-modules/utf8` repository, `script-modules/scroll-list.lua`, `script-modules/sha1.lua`, `script-modules/utf8_data.lua` and `script-modules/input-console.lua`) in MPV folder? Should the script-modules folder be together with the other ones (scripts, scripts-opts) as it is in your repository, or should I drop the .lua files inside the scripts folder? I've try different ways and none of them worked so far.

**Comment by zenwarr** [comment]
The repository contents represents `.mpv` directory. So repository file structure should be kept as it.

If you want to install `sub-search` extension only, you only need extra files specified in its description, any other files or directories in the repository are not required for this extension to work (except the script file itself, of course).

So you should:
- create `script-modules` dir in your mpv dir
- copy modules listed in description inside it (for example, `script-modules/scroll-list.lua` should be copied in `script-modules/scroll-list.lua`)
- clone utf8 repository (in `script-modules` directory too)
- create `scripts` dir in your mpv dir
- copy `scripts/sub-search.lua` inside `scripts/sub-search.lua`

If it doesn't work for you, provide more details on what errors you have.

**Comment by tXJtqlb3bbeKD1yW8SV7** [comment]
I figured it out, thanks. It seems that I'd messed up the utf8 repository. By the way, is there any chance that the .vtt format will be supported in the future?

**Comment by zenwarr** [comment]
> is there any chance that the .vtt format will be supported in the future?

Yes, I plan to support more subtitle formats, it would be nice

**Comment by zenwarr** [comment]
You can subscribe to #3 to receive an update on it
