### ISSUE TITLE
[clock.lua] disabled by default

### ISSUE THREAD

**Issue by bachig26** [zenwarr/mpv-config#6]
I like the script which I use daily since I found but sometimes I don't want it be enabled by default.

I looked at lua scripting and I'm not familiar with them, can you help me to set the script as disabled by default and can be toggled by the input keybind on used command.

**Comment by zenwarr** [comment]
Thank you for using the script! Now (if you update the script) you can make it disabled by default. You need to create `script-opts/clock.conf` file in your mpv configuration directory (for example, `~/.config/mpv/script-opts/clock.conf` with the following contents:

```
enabled_by_default=no
```
