### ISSUE TITLE
[pause-indicator] still seeing the default indicator

### ISSUE THREAD

**Issue by bachig26** [zenwarr/mpv-config#7]
i thought placing this `pause-indicator.lua` will replace the default/old play/pause indicator but still I'm seeing both the default and the new indicator in the mpv.

please help me how can I disable the default indicator.

**Comment by zenwarr** [comment]
Sorry, what do you mean by default indicator? Could you provide a screenshot?

**Comment by bachig26** [comment]
> Sorry, what do you mean by default indicator? Could you provide a screenshot?

As you can see in the clip, I can see the play/pause from the mpv (osc/uosc, which I'm not sure) and the script in top right corner.

### my config zip (in case)

[portable_config.zip](https://github.com/zenwarr/mpv-config/files/10887621/portable_config.zip)
         _I'm using the mpv via scoop, the config's are packed in the `C:\Users\USER\scoop\apps\mpv\current\portable_config` location._
 
### Clip:

https://user-images.githubusercontent.com/96393348/222879830-acadb673-7fff-4df4-ae07-41c1f001ed04.mp4

**Comment by zenwarr** [comment]
I see you use uosc as the default OSC replacement. The pause indicator is provided by it, and I can't see an easy way to replace it, unfortunately

**Comment by bachig26** [comment]
> I see you use uosc as the default OSC replacement. The pause indicator is provided by it, and I can't see an easy way to replace it, unfortunately

👍✌

**Comment by zenwarr** [comment]
I checked uosc config, and looks like you can disable uosc indicator by setting `pause_indicator=none` instead of `pause_indicator=flash` in `script-opts/uosc.conf` file 😄

**Comment by bachig26** [comment]
> I checked uosc config, and looks like you can disable uosc indicator by setting `pause_indicator=none` instead of `pause_indicator=flash` in `script-opts/uosc.conf` file 😄

awesome it works.... thank you so much.
